BoxLayout:
    orientation: 'horizontal'
    TextInput:
        id: input_miles
        text: '34'
        font_size: 48
        multiline: False
    BoxLayout:
        orientation: 'vertical'
        Button:
            Text: 'Up'
        Button:
            Text: 'Down'
    Button:
        Text: 'Convert m to km'
    Label:
        id: output_label
        font_size: 48
        color: (1, 0, 1, 1)
